### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by CopperHusky6475** [anthturner/UniFiSharp#17]
using UniFiSharp;

string uri = ""; // I removed my URI
string username = ""; // Removed my username
string password = ""; // Removed my password

UniFiApi? api = new UniFiApi(new Uri(uri), username, password, ignoreSslValidation: true, useModernApi:false);

// Manually calling. Authenticate() forces the API to proactively authenticate.
// Otherwise, the request will be automatically authenticated upon receiving an unauthorized error.
await api.Authenticate();

// ... for example, enumerate all UniFi devices known by the controller:
IEnumerable<UniFiSharp.Json.JsonNetworkDevice> uniFiDevices = await api.NetworkDeviceList(); // Get error here

Console.WriteLine(uniFiDevices.Count());

error I get:

Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=JSON integer 4294966675 is too large or small for an Int32. Path 'data[32].vap_table[1].tx_retries', line 1, position 849700.
  Source=UniFiSharp
  StackTrace:
   at UniFiSharp.DefaultUniFiRestClient.<ExecuteRequest>d__21`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UniFiSharp.DefaultUniFiRestClient.<UniFiRequestMany>d__19`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UniFiSharp.DefaultUniFiRestClient.<UniFiGetMany>d__8`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UniFiSharp.UniFiApi.<NetworkDeviceList>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\Users\********\Program.cs:line 21

  This exception was originally thrown at this call stack:
    [External Code]
    <Program>$.<Main>$(string[]) in Program.cs

**Comment by anthturner** [comment]
Fixed in #21
